#ifndef MML_BGM_STAGE2_H
#define MML_BGM_STAGE2_H

static const char * const mml_bgm_stage2 = 
    "T130V15 $B30"
    "[0"
        "[2"
            "Q2"
            "O5 D F# A8 G8 E8 C#8  "
            "O5 D F# A R4"
            "O5 D F# A8 G8 E8 C#8  "
            "O5 D F#8 E8 D R4"
        "]"
        "[2"
            "Q2"
            "O5 B4 A8 G8"
            "O5 A4 F#8 D8"
            "O5 G4 E8 A8 F#4 R4"
            "O5 E4 F#8 G8"
            "O5 F#4 E8 D8"
        "|"
            "O5 G4 A8 B8 A4 R4"
        "]"
        "O5 E4 D8 C#8 D4 R4"
    "]"
    ","
    "T130V15 $B30"
    "[0"
        "Q2"
        "O2L8"
        "[8"
            "O2 D >D <D> D"
            "O1 A >A <A >A"
        "]"
        "[2"
            "O2 G > G <G >G"
            "O2 D >D <D> D"
            "O1 A >A <A >A"
            "O2 D >D <D> D"
        "|"
            "O2 G >G <G> G"
            "O2 D >D <D> D"
            "O2 G > G <G >G"
            "O2 A > A <A >A"
        "]"
        "O2 E >E <E >E"
        "O2 D >D <D> D"
        "O1 A >A <A >A"
        "O2 D >D <D> D"
    "]"
    ","
    "T130V15 $B30"
    "[0"
        "[2"
            "L4 $E0"
            "Q2"
            "O4 A >D E8 D8 C#8 <A8  "
            "O4 A >D F# R4"
            "O4 A >D E8 D8 C#8 <A8  "
            "O4 A >D8 C#8 "
        "|"
            "<A R4"
        "]"
        "Q4<A8 Q2"
        "L8"
        "$E1$A0$H20$D100$S80$F100"
        "O6  D F# A"
        "[2"
            "O6 G B > D < B"
            "O6 D F# A F#"
            "O5 A >C# E A"
            "O6 F# D< A F#"
            "O6 E G B >E "
            "O6 D F# A F#"
        "|"
            "O6 G <B > D G"
            "O6 A C# E A"
        "]"
        "O5 A > C# E C#"
        "O6 D F# A > D"
    "]"
;

#endif // MML_BGM_STAGE2_H
