#ifndef MGC_ITEM_DESCRIPTORS_MENU_H
#define MGC_ITEM_DESCRIPTORS_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

#include "item_descriptors.h"

enum item_decriptors_menu_index {
    ITEM_DESCRIPTORS_MENU_ITEM1 = 0,
    ITEM_DESCRIPTORS_MENU_ITEM2,
    ITEM_DESCRIPTORS_MENU_ITEM3,
    ITEM_DESCRIPTORS_MENU_ITEM4,
    ITEM_DESCRIPTORS_MENU_ITEM5,
    ITEM_DESCRIPTORS_MENU_ITEM6,
    ITEM_DESCRIPTORS_MENU_ITEM7,
    ITEM_DESCRIPTORS_MENU_ITEM8,
    ITEM_DESCRIPTORS_MENU_ITEM9,
    ITEM_DESCRIPTORS_MENU_ITEM10,
    ITEM_DESCRIPTORS_MENU_ITEM11,
    ITEM_DESCRIPTORS_MENU_ITEM12,
    ITEM_DESCRIPTORS_MENU_ITEM13,
    ITEM_DESCRIPTORS_MENU_ITEM14,
    ITEM_DESCRIPTORS_MENU_ITEM15,
    ITEM_DESCRIPTORS_MENU_ITEM16,
    ITEM_DESCRIPTORS_MENU_ITEM17,
    ITEM_DESCRIPTORS_MENU_ITEM18,
    ITEM_DESCRIPTORS_MENU_ITEM19,
    ITEM_DESCRIPTORS_MENU_ITEM20,
    COUNT_ITEM_DESCRIPTOR_MENU
};

enum weapon_decriptors_menu_index {
    WEAPON_DESCRIPTORS_MENU_WEAPON1 = 0,
    WEAPON_DESCRIPTORS_MENU_WEAPON2,
    COUNT_WEAPON_DESCRIPTOR_MENU
};

extern const item_descriptors_t item_descriptors_menu;
extern const item_descriptors_t weapon_descriptors_menu;

#ifdef __cplusplus
}
#endif

#endif/*MGC_ITEM_DESCRIPTORS_MENU_H*/

