#ifndef MGC_ITEM_DESCRIPTORS_ITEM_H
#define MGC_ITEM_DESCRIPTORS_ITEM_H

#ifdef __cplusplus
extern "C" {
#endif

#include "item_descriptors.h"

enum item_decriptors_item_index {
    ITEM_DESCRIPTORS_ITEM1 = 0,
    ITEM_DESCRIPTORS_ITEM2,
    ITEM_DESCRIPTORS_ITEM3,
    ITEM_DESCRIPTORS_ITEM4,
    ITEM_DESCRIPTORS_ITEM5,
    ITEM_DESCRIPTORS_ITEM6,
    ITEM_DESCRIPTORS_ITEM7,
    ITEM_DESCRIPTORS_ITEM8,
    ITEM_DESCRIPTORS_ITEM9,
    ITEM_DESCRIPTORS_ITEM10,
    ITEM_DESCRIPTORS_ITEM11,
    ITEM_DESCRIPTORS_ITEM12,
    ITEM_DESCRIPTORS_ITEM13,
    ITEM_DESCRIPTORS_ITEM14,
    ITEM_DESCRIPTORS_ITEM15,
    ITEM_DESCRIPTORS_ITEM16,
    ITEM_DESCRIPTORS_ITEM17,
    ITEM_DESCRIPTORS_ITEM18,
    ITEM_DESCRIPTORS_ITEM19,
    ITEM_DESCRIPTORS_ITEM20,
    COUNT_ITEM_DESCRIPTOR_ITEM
};


extern const item_descriptors_t item_descriptors_item;

#ifdef __cplusplus
}
#endif

#endif/*MGC_ITEM_DESCRIPTORS_ITEM_H*/

